- name: Install package
  hosts: all
  become: true

  tasks:
    - name: Install nginx (Ubu)
      apt:
        name: nginx
        state: present
    - name: Install screen (Ubu)
      apt:
        name: screen
        state: present
